### ISSUE TITLE
Windows 10 - Microphone Tray Icon

### ISSUE THREAD

**Issue by alextatham** [sipsorcery/sipsorcery-media#4] opened 2020-04-23 12:54 UTC
Hi,

I'm testing these libraries for a project and have noticed an unusual symptom on Windows 10.

I've used the example code for placing an outgoing call from the main sipsorcery library.  I edit the configuration to provide my registration information for the SIP server I'm using.  I make a call outbound.  The call connects with audio and appears to work fine.  While the call is live, the microphone symbol in the Windows 10 tray appears and the disappears in a loop very quickly almost too fast to see.

If I repeat the process changing the audiooptions to select silence as the media source for audio, as you would expect, the call works and the issue does not occur.

I'm building with Visual Studio 2019 and v4.0.43-pre of SIPSorcery and v4.042-pre of SIPSorceryMedia.

Thanks.

**Comment by sipsorcery** [comment] 2020-04-23 12:56
Duplicate of [Microphone Icon shaking](https://github.com/sipsorcery/sipsorcery/issues/191).

**Comment by sipsorcery** [comment] 2020-05-30 16:01
Closed. The [issue](https://github.com/sipsorcery/sipsorcery/issues/191) in the sipsorcery library will be kept open to track this problem.

**Closed as completed by sipsorcery** 2020-05-30 16:01 UTC
Labels: duplicate
